config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  # For details on the D SL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#top'

  get '/index' => 'posts#index'

  get '/posts' => 'posts#index'

  post '/posts' => 'posts#create'

  get '/posts/:id' => 'posts#show', as: 'post'

  get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'

  patch '/posts/:id' => 'posts#update', as: 'update_post'

  delete '/post/:id' => 'posts#destroy', as: 'destroy_post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  validates :title, :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	@post = Post.all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@post = Post.new
  end

  def index
    @posts = Post.all
    @post = Post.new
  end

  def create
  	@post = Post.new(post_params)
    if @post.save
      flash[:success] = "Book was successfully created"
      redirect_to post_path(@post)
    else
      @posts = Post.all
      render :index
    end

  end

  def show
    @post = Post.find(params[:id])
    

  end

  def edit
    @post = Post.find(params[:id])
    
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Book was successfully created"
      redirect_to post_path(@post)
    else
      @posts = Post.all
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path

  end
  private

  def post_params
  	params.require(:post).permit(:title, :body)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
<div id="error_expanation" class="alert alert-danger">
	<ul>
		<% @post.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>

</div>
<% end %>



<h1>Edit Book</h1>
<%= form_for(@post) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title,class: "book_title"%>
    <h4>Body</h4>
    <%= f.text_area :body,class: "book_body"%>
    <%= f.submit 'Update Book' %>
<span>
	<%= link_to "show", post_path(@post.id),class: "show#{@post.id}" %>
</span>
<span>
	<%= link_to "back", posts_path,class:"back"%>
</span>
<% end %>

app/views/posts/index.html.erb
<h1>books</h1>
<% if @post.errors.any? %>
<div id="error_expanation" class="alert alert-danger">
	<ul>
		<% @post.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>

</div>
<% end %>

<table>
	<thead>
		<tr>
			<th>title</th>
			<th>body</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td><%= post.title %></td>
				<td><%= post.body %></td>
				<td><%= link_to "show", post_path(post.id),class:"show_#{post.id}"%></td>
				<td><%= link_to "edit", edit_post_path(post.id),class:"edit_#{post.id}"%></td>
				<td><%= link_to "destroy", destroy_post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？",class:"destroy_#{post.id}"%></td>
			</tr>
		<% end %>
	</tbody>

</table>
<p>New book</p>

<%= form_for(@post) do |f| %>

	<h4>title</h4>
	<%= f.text_field :title, class:"book_title" %>

	<h4>body</h4>
	<%= f.text_area :body, class:"book_body" %>

	<%= f.submit 'Create Book' %>

<% end %>

app/views/posts/new.html.erb
<h1>New book</h1>

<%= form_for(@post) do |f|%>

	<h4>title</h4>
	<%= f.text_field :title %>

	<h4>body</h4>
	<%= f.text_area :body %>

	<%= f.submit 'Create Book' %>

<% end %>

app/views/posts/show.html.erb
 <% if flash[:success] %>
 <div class="flash">
 	<%= flash[:success] %>

 </div>
 <% end %>

<h1>title</h1>
<%= @post.title %>
<h1>body</h1>
<%= @post.body %>

<span>
	<%= link_to "edit", edit_post_path(@post.id) %>
</span>
<span>
	<%= link_to "back", posts_path(@post.id),class:"back" %>
</span>

</span>

app/views/root/top.html.erb
<h1>ようこそbookersへ！</h1>
<p>
	bookersでは、さまざまな書籍に関するあなたの意見や<br>
	印象を共有し交換することができます
</p>
<span>
	<%= link_to "start", "/posts" %>
</span>